---
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: certbot
  matrix:
    - MOLECULE_DISTRO: debian:stretch
    - MOLECULE_DISTRO: debian:stretch
      MOLECULE_PLAYBOOK: pip_route53_playbook.yml
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: centos:7
      MOLECULE_PLAYBOOK: pip_route53_playbook.yml
    - MOLECULE_DISTRO: ubuntu:xenial
    - MOLECULE_DISTRO: ubuntu:xenial
      MOLECULE_PLAYBOOK: pip_route53_playbook.yml
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: ubuntu:bionic
      MOLECULE_PLAYBOOK: pip_route53_playbook.yml

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME ericsysmin.$ROLE_NAME
  - cd ericsysmin.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
