---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install pip
      package: name=python-pip
  roles:
    - role: ericsysmin.epel
    - role: ericsysmin.certbot
      certbot_pkg_mgr: pip
      certbot_plugins: ['dns-route53']
