---
- name: certbot | PyPI | Upgrade pip, setuptools, and pyopenssl as required
  pip: name={{ item }} state=latest
  loop:
    - pip
    - setuptools
    - pyopenssl

- name: certbot | PyPI | Install certbot {{ certbot_pip_version }}
  pip:
    name: certbot=={{ certbot_pip_version }}

- name: certbot | PyPI | Install certbot plugins
  pip:
    name: "certbot-{{ item }}=={{ certbot_pip_version }}"
  loop: "{{ certbot_plugins }}"
  when: certbot_plugins is defined
